# DATA ENGINEERING LIFECYCLE
# PYTHON

Data scientists often use or start data that is already available either in csv formart a .db,anAPI,dahboard but in the real production environment that data doesnt  just appear but goes through a procces for it to be available.that procces is caled the data engineering lifecycle<br>

this procces is essential to a data scientist since the quality of your data determines the quality of your analysis and  the quality of perfomance  of your models.<br>

data engineering lifecycle has the following connected steps
- data generation
- data storage
- data ingestion
- data transformation
- data serving


**Data Generation** is the point at wgich data is  captured or generated<br>
**Data Storage**  saving the data in an organised manner once it has been cleaned<br>
**Data Transformation** it is the procces of preparing raw data<br>
**Data Ingestion** procces of loading data into our system<br>
**Data serving** making data available to the end user<br>


## DATA ENGINEERING LIFECYCLE WITH PYTHON

Python plays a major role in the data engineering lifecycle using tools like pandas and numpy.<br>
these tools help python in reading files cleaning and transforming data for analysis.<br>
pandas  is essential for  manupilating data:reading files,cleaning,ingestion,analysis and transformation.<br>
numpy is mainly good for data generation<br>



## DATA GENERATION
sensor data

In [26]:
import numpy as np
import pandas as pd
np.random.seed(23)

sensor_temp_data=np.random.uniform(15,35, (10, 5))
print(sensor_temp_data)


[[25.34595768 33.93925208 30.30919519 20.64791688 19.42090727]
 [28.7244417  18.34278406 22.84884933 27.36104695 23.2386019 ]
 [15.04929762 32.68064365 32.69895077 21.00819379 26.7916373 ]
 [34.56853832 31.90187644 16.30150878 20.89488929 20.75868882]
 [31.44932678 27.52366076 17.20955428 15.01057622 33.84332466]
 [17.83001515 23.43193052 21.9297888  32.39570169 23.57203625]
 [31.57502969 29.35703676 17.38453388 26.92768345 17.59512595]
 [16.55068183 31.62410511 24.2877123  18.24024958 25.95950584]
 [26.76971644 30.47226338 28.11690916 26.15413519 18.56494533]
 [19.81167062 25.12109265 22.93491398 24.66110371 34.11479682]]


## DATA STORAGE

In [27]:
df = [
    {"morning":[23,34,21,20,14],
     "mid_day":[30,32,28,29,31],
     "evening":[25,27,22,24,26]}
]
pdf1=pd.DataFrame(df)
pdf1.to_csv("temp_data.csv", index=False)

## DATA INGESTION

In [28]:
pd.read_csv("temp_data.csv").head()

,morning,mid_day,evening
0,"[23, 34, 21, 20, 14]","[30, 32, 28, 29, 31]","[25, 27, 22, 24, 26]"


In [29]:
pdf1['avg_temp'] = [(pdf1['morning'] + pdf1['mid_day'] + pdf1['evening'])/ 3]

TypeError: unsupported operand type(s) for /: 'list' and 'int'

## DATA SERVING 
putting it in a data format that is end user friendly<br>

## DATA PIPELINE


In [ ]:
#step 1 Data generation
students = pd.DataFrame({
    "names":["Steve","Reginah","Grace","joel"],
    "scores":[56,78,45,np.nan]})

# students.to_csv("students_info.csv",index=False)

# #step3 Data ingestion
# #reading into memory
# pd.read_csv("students_info.csv")
# #step 4 :Data Transformation
# df_scores = pd.read_csv("students_info.csv")

NameError: name 'pd' is not defined

## DATA ENGINEERING LIFECYCLE WITH SQL

### 

-sql is crucial for structured data and relational databases<br>
-it helps create  tables insert tables update tables delete records join tables perform aggregation functions and retrive data for analysis and reporting.<br>
-this therefore makes sql very important for storage ingestion transformation and the storing of the data<br>
-while python is usefull for working with data after loading it in the memory sql is often used to manage and transform data within a database<br>



### DATA STORAGE

In [12]:
import sqlite3
conn= sqlite3.connect("students.db")

### STORAGE


In [14]:
creating_tables="""
    CREATE TABLE IF  NOT EXISTS student_info(
        student_id interger PRIMARY KEY,
        name TEXT NOT NULL,
        phone TEXT NOT NULL,
        email TEXT UNIQUE,
        course TEXT NOT NULL,
        profile_pic BLOB
    )

"""
conn.executescript(creating_tables)

## INGESTION

In [18]:
inserting_data="""
INSERT INTO student_info(name,phone,email,course,profile_pic)
VALUES
('sharleen','0713234456','sharleen@school.com','Data Science','qr.png'),
('Steve','0712434662','steve@school.com','Software Engineering','pic.png'),

('Grace','','grace@school.com','Cyber security','');

"""
conn.executescript(inserting_data)

## TRANSFORMATION

In [32]:
transformation="""
DELETE * FROM student_info
WHERE course='';
UPDATE student_info
phone='0533377733'
profile_pic='some.png'

WHERE student_id =3;
"""
conn.executescript(transformation)

OperationalError: near "*": syntax error

### SERVING

In [34]:
conn.execute("""SELECT * FROM student_info
             WHERE course ='Data Science'
             ORDER BY name DESC;
             """,conn)
students_in_ds.csv("students_in_ds.csv",index=False)


ProgrammingError: parameters are of unsupported type